accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView

from . import views, forms

app_name='accounts'

urlpatterns = [
    path(
        'signup/',
        views.SignUpView.as_view(),
        name='signup',
    ),
    path(
        'login/',
        auth_views.LoginView.as_view(
            template_name='accounts/login.html',
            authentication_form=forms.CustomAuthenticationForm
        ),
        name='login',
    ),
    path(
        'activate/<uidb64>/<token>',
        views.ActivateAccount.as_view(),
        name='activate',
    ),
    path(
        'logout',
        auth_views.LogoutView.as_view(),
        name='logout'
    ),
    path('password_reset/',
        views.PasswordReset.as_view(),
        name='password_reset',
    ),
    path('password_reset/done/',
        auth_views.PasswordResetDoneView.as_view(
            template_name='accounts/password_reset_done.html'
        ),
        name='password_reset_done'
    ),
    path('reset/<uidb64>/<token>/',
        views.PasswordResetConfirm.as_view(),
        name='password_reset_confirm'
    ),
    path(
        'reset/done/',
        auth_views.PasswordResetCompleteView.as_view(
            template_name='accounts/password_reset_complete.html'
        ),
        name='password_reset_complete'
    ),
    path('change_password/',
        auth_views.PasswordChangeView.as_view(
            template_name='accounts/change_password.html'
        ),
        name='change_password'
    ),
    path('password_change/done/',
        auth_views.PasswordChangeView.as_view(
            template_name='accounts/password_change_done.html'
        ),
    ),
    path('set_password/<uidb64>/<token>/',
        views.SetPassword.as_view(),
        name='set_password'
    ),
    path('new_user/',
        views.AddUser.as_view(),
        name='new_user'
    ),
    path('user_list',
        views.ActiveUserListView.as_view(),
        name='user_list'
    ),
    # path('user_detail/<pk>/',
    #     views.UserDetailView.as_view(),
    #     name='user_detail'
    # ),
    path('user_update/<pk>/',
        views.UpdateUser.as_view(),
        name='user_update'
    ),
    path('sent_mail_message',
        TemplateView.as_view(
            template_name='accounts/sent_mail_message.html',
        ),
        name='sent_mail_message',
    ),
    path('link_expired',
        TemplateView.as_view(
            template_name='accounts/link_expired.html',
        ),
        name='link_expired'
    ),
    path('email_verified',
        TemplateView.as_view(
            template_name='accounts/email_verified.html',
        ),
        name='email_verified'
    ),
    path('password_set_message',
        TemplateView.as_view(
            template_name='accounts/password_set_message.html'
        ),
        name='password_set_message',
    ),
    path('company/<int:pk>/settings/',
        views.UpdateCompany.as_view(),
        name='company_settings',
    )
]

eventage/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static


from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path(
        '',
        views.HomeView.as_view(),
        name='home'
    ),
    path(
        'accounts/',
        include(
            'accounts.urls',
            namespace='accounts'
        )
    ),
    path(
        'accounts/',
        include(
            'django.contrib.auth.urls'
        )
    ),
    path(
        'events/',
        include(
            'pageGenerator.urls',
            namespace='pageGenerator'
        )
    ),
    path('error-404/',
        TemplateView.as_view(template_name='error_404.html'),
        name='error_404',
    ),
    path('error-403/',
        TemplateView.as_view(template_name='error_403.html'),
        name='error_403',
    ),
    path('thankyou/',
        TemplateView.as_view(template_name='thankyou.html'),
        name='thankyou',
    ),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import PasswordResetForm
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.decorators import method_decorator
from django.template.loader import render_to_string
# from django.core.mail import send_mail
from django.views import View
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import FormView, CreateView, UpdateView
from django.views.generic import TemplateView
from django.views.decorators.csrf import csrf_protect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse

import requests

from . import models, forms, tokens, utils, mixins

#creates email message to inject into email template
def get_message(request, user, email_template):
    current_site = get_current_site(request)
    return render_to_string(
        email_template,
        {
            'user':user,
            'domain':current_site.domain,
            'uid': urlsafe_base64_encode(force_bytes(user.pk)),
            'token': tokens.account_activation_token.make_token(user)
        }
    )

# creates a company and its supervisor
class SignUpView(TemplateView):
    template_name = 'accounts/signup.html'

    def post(self, request, *args, **kwargs):
        user_form = forms.UserCreationForm(request.POST)
        company_form = forms.CompanyCreationForm(request.POST)
        if all({user_form.is_valid(), company_form.is_valid()}):

            user = user_form.save(commit=False)
            user.is_active = False

            company = company_form.save()

            user.company = company
            user.save()

            mail_subject = 'Activate Your Eventage Account'
            email_template = 'accounts/activate_account_email_body.html'
            to_email = user_form.cleaned_data.get('email')

            utils.send_mail(
                to_email,
                mail_subject,
                get_message(request, user, email_template)
            )

            return HttpResponseRedirect(reverse('accounts:sent_mail_message'))

        return render(request, self.template_name, {
            'user_form':user_form,
            'company_form':company_form
        })

    def get(self, request, *args, **kwargs):

        if request.user.is_authenticated:
            return HttpResponseRedirect(reverse('home'))

        user_form = forms.UserCreationForm()
        company_form = forms.CompanyCreationForm()

        return render(request, self.template_name, {
            'user_form':user_form,
            'company_form':company_form
        })

# activates account - after clicking link sent to email
class ActivateAccount(View):
    def get(self, request, *args, **kwargs):
        try:
            uid = force_text(urlsafe_base64_decode(kwargs['uidb64']))
            user = models.User.objects.get(pk=uid)
            assert(
                tokens.account_activation_token.check_token(
                    user,
                    kwargs['token']
                )
            )
            user.is_active = True
            user.save()
            user.company.is_active = True
            user.company.save()
        except (models.User.DoesNotExist, AssertionError):
            return HttpResponseRedirect(reverse('accounts:link_expired'))
        return HttpResponseRedirect(reverse('accounts:email_verified'))

# @method_decorator(csrf_protect, name='dispatch')
class PasswordReset(FormView):
    template_name = 'accounts/password_reset_form.html'
    form_class = PasswordResetForm
    success_url = reverse_lazy('accounts:password_reset_done')

    def form_valid(self, form):
        email = form.cleaned_data.get('email')
        try:
            user = models.User.objects.get(email=email)
            mail_subject = 'Reset Your Eventage Account Password'
            email_template = 'accounts/password_reset_email_body.html'
            to_email = email
            utils.send_mail(to_email, mail_subject, get_message(self.request, user, email_template))
        except models.User.DoesNotExist:
            form.add_error(None, 'User with this email doesn\'t exist!')
            return super().form_invalid(form)
        return super().form_valid(form)

#resets password - accessed via link sent to email for forgotten password
class PasswordResetConfirm(FormView):
    form_class = forms.SetPasswordForm
    template_name = 'accounts/password_reset_confirm.html'
    success_url = reverse_lazy('accounts:password_reset_complete')

    def get(self, request, *args, **kwargs):
        try:
            uid = force_text(urlsafe_base64_decode(kwargs['uidb64']))
            user = models.User.objects.get(pk=uid)
            assert(
                tokens.account_activation_token.check_token(
                    user,
                    kwargs['token']
                )
            )
        except (models.User.DoesNotExist, AssertionError):
            return HttpResponseRedirect(reverse('accounts:link_expired'))
        return super().get(request, *args, **kwargs)

    def form_valid(self, form):
        uid = force_text(urlsafe_base64_decode(self.kwargs['uidb64']))
        user = models.User.objects.get(pk=uid)
        password = form.cleaned_data.get('password1')
        user.set_password(password)
        user.save()
        return super().form_valid(form)

# creates user - created by company manager
class AddUser(
    LoginRequiredMixin,
    mixins.ManagerRequiredMixin,
    FormView
):
    form_class = forms.AddUserForm
    template_name = 'accounts/new_user.html'
    success_url = reverse_lazy('accounts:user_list')

    def form_valid(self, form):
        company = self.request.user.company
        new_user = form.save(commit=False)
        new_user.company = company
        new_user.set_unusable_password()
        new_user.save()
        mail_subject = 'You were added by ' + company.name + ' to eventage.com'
        email_template = 'accounts/set_password_email_body.html'
        to_email = form.cleaned_data.get('email')
        utils.send_mail(to_email, mail_subject, get_message(self.request, new_user, email_template))
        return super().form_valid(form)

# sets password for new user added by a company
class SetPassword(FormView):
    form_class = forms.SetPasswordForm
    template_name = 'accounts/set_password.html'
    success_url = reverse_lazy('accounts:password_set_message')

    def get(self, request, *args, **kwargs):
        try:
            uid = force_text(urlsafe_base64_decode(kwargs['uidb64']))
            user = models.User.objects.get(pk=uid)
            assert(
                tokens.account_activation_token.check_token(
                    user,
                    kwargs['token']
                )
            )
        except (models.User.DoesNotExist, AssertionError):
            return HttpResponseRedirect(
                reverse('accounts:link_expired')
            )
        return super().get(request, *args, **kwargs)

    def form_valid(self, form):
        uid = force_text(urlsafe_base64_decode(self.kwargs['uidb64']))
        user = models.User.objects.get(pk=uid)
        password = form.cleaned_data.get('password1')
        user.set_password(password)
        user.save()
        return super().form_valid(form)

#returns list of users
class ActiveUserListView(LoginRequiredMixin, ListView):
    model = models.User
    template_name='accounts/user_list.html'

    def get(self, request, *args, **kwargs):
        if request.user.type == 'n':
            return redirect('error_404')
        return super().get(request, *args, **kwargs)

    def get_queryset(self):
        return models.User.objects.filter(
            is_active=True,
            company=self.request.user.company,
        )

# class UserDetailView(LoginRequiredMixin, DetailView):
#     template_name='accounts/user_detail.html'
#     model = models.User
#     context_object_name = 'user_obj'

#updates user details
class UpdateUser(
    LoginRequiredMixin,
    mixins.ManagerRequiredMixin,
    mixins.SameCompanyOnlyMixin,
    UpdateView
):
    form_class = forms.UserUpdateForm
    model = models.User
    template_name = 'accounts/user_update.html'
    success_url = reverse_lazy('accounts:user_list')
    context_object_name = 'user_obj'

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

    def get_form_kwargs(self, *args, **kwargs):
        kwargs = super().get_form_kwargs(*args, **kwargs)
        kwargs['user'] = self.request.user
        return kwargs

class UpdateCompany(
    LoginRequiredMixin,
    mixins.ManagerRequiredMixin,
    DetailView
):
    model = models.Company
    context_object_name = 'company'
    template_name = 'accounts/company_settings.html'

    def post(self, request, *args, **kwargs):
        company = request.user.company
        if 'submit' in request.POST:
            company_form = forms.CompanyUpdateForm(
                request.POST,
                instance=company
            )
            event_extra_formset = forms.EventExtraFieldFormset(
                request.POST,
                instance=company,
                queryset=models.EventExtraField.objects.filter(
                    company=company,
                    is_active=True
                ),
                prefix='event_extra'
            )
            if all({
                company_form.is_valid(),
                event_extra_formset.is_valid()
            }):
                company_form.save()
                event_extra_formset.save()

accounts/templates/accounts/activate_account_email_body.html
{% load static %}

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html dir="ltr" xmlns="http://www.w3.org/1999/xhtml">

<head>
    <meta name="viewport" content="width=device-width" />
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <title>Eventage Email Verification Email</title>
</head>

<body style="margin:0px; background: #f8f8f8; ">
    <div width="100%" style="background: #f8f8f8; padding: 0px 0px; font-family:arial; line-height:28px; height:100%;  width: 100%; color: #514d6a;">
        <div style="max-width: 700px; padding:50px 0;  margin: 0px auto; font-size: 14px">
            <table border="0" cellpadding="0" cellspacing="0" style="width: 100%; margin-bottom: 10px">
                <tbody>
                    <tr>
                        <td style="vertical-align: top; padding-bottom:10px;" align="center"><a href="http://{{domain|escape}}" target="_blank"><img src="cid:logo.png" alt="Eventage" height="50" width="50" style="border:none;"></a>
                        <h2>Eventage</h2>
                      </a> </td>
                    </tr>
                </tbody>
            </table>
            <div style="padding: 40px; background: #fff;">
                <table border="0" cellpadding="0" cellspacing="0" style="width: 100%;">
                    <tbody>
                        <tr>
                            <td><b>Dear {{user.first_name | escape}},</b>
                                <p>This is to inform you that, Your account with Eventage has been created successfully. Please verify your email to login.</p>
                                <a href="http://{{domain|escape}}{% url 'accounts:activate' uidb64=uid token=token %}" style="display: inline-block; padding: 11px 30px; margin: 20px 0px 30px; font-size: 15px; color: #fff; background: #4fc3f7; border-radius: 60px; text-decoration:none;"> Verify Email </a></td>
                        </tr>
                        <tr>
                            <td style="border-top:1px solid #f6f6f6; padding-top:20px; color:#777">If the button above does not work, try copying and pasting the URL into your browser. If you continue to have problems, please contact your administrator/supervisor.</td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <div style="text-align: center; font-size: 12px; color: #b2b2b5; margin-top: 20px">
              <p> This is a system generated mail. Please don't reply to this email.
                  <br>
              </p>
            </div>
        </div>
    </div>
</body>

</html>

accounts/templates/accounts/email_verified.html
<!DOCTYPE html>
{% load static %}
<html dir="ltr">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- Favicon icon -->
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'assets/images/logos/logo.png' %}">
    <title>Email Verified</title>
	<link rel="canonical" href="https://www.wrappixel.com/templates/ampleadmin/" />
    <!-- Custom CSS -->
    <link href="{% static 'dist/css/style.min.css' %}" rel="stylesheet">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
<![endif]-->
</head>

<body>
    <div class="main-wrapper">
        <!-- ============================================================== -->
        <!-- Preloader - style you can find in spinners.css -->
        <!-- ============================================================== -->
        <div class="preloader">
            <div class="lds-ripple">
                <div class="lds-pos"></div>
                <div class="lds-pos"></div>
            </div>
        </div>
        <!-- ============================================================== -->
        <!-- Preloader - style you can find in spinners.css -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Login box.scss -->
        <!-- ============================================================== -->
        <div class="auth-wrapper d-flex no-block justify-content-center align-items-center" style="background:#f6f6f6;">
            <div class="auth-box" style="max-width:100%!important;">
                <div id="loginform">
                    <div class="row">
                        <div class="col-sm-12">
                            <h2 class="mb-0" style="text-align:center;">Your email has been successfully verified. You can <a href="{% url 'accounts:login' %}">login</a> now.</h2>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- ============================================================== -->
        <!-- Login box.scss -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Page wrapper scss in scafholding.scss -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Page wrapper scss in scafholding.scss -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Right Sidebar -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Right Sidebar -->
        <!-- ============================================================== -->
    </div>
    <!-- ============================================================== -->
    <!-- All Required js -->
    <!-- ============================================================== -->
    <script src="{% static 'assets/libs/jquery/dist/jquery.min.js' %}"></script>
    <!-- Bootstrap tether Core JavaScript -->
    <script src="{% static 'assets/libs/popper.js/dist/umd/popper.min.js' %}"></script>
    <script src="{% static 'assets/libs/bootstrap/dist/js/bootstrap.min.js' %}"></script>
    <!-- ============================================================== -->
    <!-- This page plugin js -->
    <!-- ============================================================== -->
    <script>
    $('[data-toggle="tooltip"]').tooltip();
    $(".preloader").fadeOut();
    // ==============================================================
    // Login and Recover Password
    // ==============================================================
    $('#to-recover').on("click", function() {
        $("#loginform").slideUp();
        $("#recoverform").fadeIn();
    });
    </script>
</body>

</html>

accounts/templates/accounts/login.html
<!DOCTYPE html>
{% load static %}
<html dir="ltr">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- Favicon icon -->
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'assets/images/logos/logo.png' %}">
    <title>Sign In</title>
	<link rel="canonical" href="https://www.wrappixel.com/templates/ampleadmin/" />
    <!-- Custom CSS -->
    <link href="{% static 'dist/css/style.min.css' %}" rel="stylesheet">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
<![endif]-->
</head>

<body>
    <div class="main-wrapper">
        <!-- ============================================================== -->
        <!-- Preloader - style you can find in spinners.css -->
        <!-- ============================================================== -->
        <div class="preloader">
            <div class="lds-ripple">
                <div class="lds-pos"></div>
                <div class="lds-pos"></div>
            </div>
        </div>
        <!-- ============================================================== -->
        <!-- Preloader - style you can find in spinners.css -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Login box.scss -->
        <!-- ============================================================== -->
        <div class="auth-wrapper d-flex no-block justify-content-center align-items-center" style="background:#f6f6f6;">
            <div class="auth-box">
                <div id="loginform">
                    <div class="logo">
                        <span class="db"><img src="{% static 'assets/images/logos/logo.png' %}" alt="homepage" class="light-logo" height="43" width="43" /></span>
                        <h5 class="font-medium mb-3 mt-3">Sign In</h5>
                    </div>
                    <!-- Form -->
                    <div class="row">
                        <div class="col-12">
                            <form class="form-horizontal mt-3" method="post">
                                {% csrf_token %}
                                <small style="color:red;">{{form.non_field_errors | striptags}}</small>
                                <small style="color:red;">{{form.username.errors | striptags}}</small>
                                <div class="input-group mb-3">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text" id="basic-addon2"><i class="ti-email"></i></span>
                                    </div>
                                    <input type="email" name="username" autofocus required class="form-control form-control-lg" placeholder="Email" aria-label="Email" aria-describedby="basic-addon1">
                                </div>
                                <small style="color:red;">{{form.password.errors | striptags}}</small>
                                <div class="input-group mb-3">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text" id="basic-addon2"><i class="ti-pencil"></i></span>
                                    </div>
                                    <input type="password" name="password" required class="form-control form-control-lg" placeholder="Password" aria-label="Password" aria-describedby="basic-addon1">
                                </div>
                                <div class="form-group row">
                                    <div class="col-md-12">
                                        <div class="custom-control custom-checkbox">
                                            <!-- <input type="checkbox" class="custom-control-input" id="customCheck1">
                                            <label class="custom-control-label" for="customCheck1">Remember me</label> -->
                                            <a href="{% url 'accounts:password_reset' %}" id="to-recover" class="text-dark float-right"><i class="fa fa-lock mr-1"></i> Forgot password?</a>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group text-center">
                                    <div class="col-xs-12 pb-3">
                                        <button class="btn btn-block btn-lg btn-info" type="submit">Log In</button>
                                    </div>
                                </div>
                                <div class="form-group mb-0 mt-2">
                                    <div class="col-sm-12 text-center">
                                        Don't have an account? <a href="{% url 'accounts:signup' %}" class="text-info ml-1"><b>Sign Up</b></a>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- ============================================================== -->
    <!-- All Required js -->
    <!-- ============================================================== -->
    <script src="{% static 'assets/libs/jquery/dist/jquery.min.js' %}"></script>
    <!-- Bootstrap tether Core JavaScript -->
    <script src="{% static 'assets/libs/popper.js/dist/umd/popper.min.js' %}"></script>
    <script src="{% static 'assets/libs/bootstrap/dist/js/bootstrap.min.js' %}"></script>
    <!-- ============================================================== -->
    <!-- This page plugin js -->
    <!-- ============================================================== -->
    <script>
    $('[data-toggle="tooltip"]').tooltip();
    $(".preloader").fadeOut();
    // ==============================================================
    // Login and Recover Password
    // ==============================================================
    $('#to-recover').on("click", function() {
        $("#loginform").slideUp();
        $("#recoverform").fadeIn();
    });
    </script>
</body>

</html>

accounts/templates/accounts/user_list.html
{% extends 'base.html' %}

{% block title %}
Users
{% endblock %}

{% block css %}

{% endblock %}

{% block breadcrumb %}
  Users
{% endblock %}

{% block buttons %}
  <li class="breadcrumb-item">
    {% if user.type != 'n' %}
    <a class="float-right breadcrumb-link" href="{% url 'accounts:new_user' %}">
      <button type="button" class="btn btn-outline-success btn-rounded btn-sm" name="button">Add New User</button>
    </a>
    {% endif %}
  </li>
{% endblock %}

{% block content %}
  <div class="page-content container-fluid">
    <div class="row">
      {% for user_obj in object_list %}
        <div class="col-lg-3 col-xlg-3 col-md-3">
            <div class="card">
                <div class="card-body">
                    {% if user.type != 'n' %}
                      {% if user.type != 'm' or user_obj.type == 'n' %}
                        <a href="{% url 'accounts:user_update' pk=user_obj.pk %}" class="float-right"><i class="mdi mdi-pencil " style="font-size:1.2em;"></i></a>
                      {% endif %}
                    {% endif %}
                    <center> <img src="{{user_obj.profile_pic.url}}" class="rounded-circle" width="150" height="150" style="object-fit:cover;" />
                        <h4 class="card-title mt-2">{{user_obj.first_name}} {{user_obj.last_name}}</h4>
                        <h6 class="card-subtitle">{% if user_obj.type == 'n' %}Agent{% else %}Manager{% endif %}</h6>
                    </center>
                </div>
                <div>
                    <hr> </div>
                <div class="card-body"> <small class="text-muted">Email address </small>
                    <h6>{{user_obj.email}}</h6> <small class="text-muted pt-4 db">Phone</small>
                    <h6>{{user_obj.phone}}</h6>
                </div>
            </div>
        </div>
      {% endfor %}
    </div>
  </div>
{% endblock %}