accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView

from . import views, forms

app_name='accounts'

urlpatterns = [
    path(
        'signup/',
        views.SignUpView.as_view(),
        name='signup',
    ),
    path(
        'login/',
        auth_views.LoginView.as_view(
            template_name='accounts/login.html',
            authentication_form=forms.CustomAuthenticationForm
        ),
        name='login',
    ),
    path(
        'activate/<uidb64>/<token>',
        views.ActivateAccount.as_view(),
        name='activate',
    ),
    path(
        'logout',
        auth_views.LogoutView.as_view(),
        name='logout'
    ),
    path('password_reset/',
        views.PasswordReset.as_view(),
        name='password_reset',
    ),
    path('password_reset/done/',
        auth_views.PasswordResetDoneView.as_view(
            template_name='accounts/password_reset_done.html'
        ),
        name='password_reset_done'
    ),
    path('reset/<uidb64>/<token>/',
        views.PasswordResetConfirm.as_view(),
        name='password_reset_confirm'
    ),
    path(
        'reset/done/',
        auth_views.PasswordResetCompleteView.as_view(
            template_name='accounts/password_reset_complete.html'
        ),
        name='password_reset_complete'
    ),
    path('change_password/',
        auth_views.PasswordChangeView.as_view(
            template_name='accounts/change_password.html'
        ),
        name='change_password'
    ),
    path('password_change/done/',
        auth_views.PasswordChangeView.as_view(
            template_name='accounts/password_change_done.html'
        ),
    ),
    path('set_password/<uidb64>/<token>/',
        views.SetPassword.as_view(),
        name='set_password'
    ),
    path('new_user/',
        views.AddUser.as_view(),
        name='new_user'
    ),
    path('user_list',
        views.ActiveUserListView.as_view(),
        name='user_list'
    ),
    # path('user_detail/<pk>/',
    #     views.UserDetailView.as_view(),
    #     name='user_detail'
    # ),
    path('user_update/<pk>/',
        views.UpdateUser.as_view(),
        name='user_update'
    ),
    path('sent_mail_message',
        TemplateView.as_view(
            template_name='accounts/sent_mail_message.html',
        ),
        name='sent_mail_message',
    ),
    path('link_expired',
        TemplateView.as_view(
            template_name='accounts/link_expired.html',
        ),
        name='link_expired'
    ),
    path('email_verified',
        TemplateView.as_view(
            template_name='accounts/email_verified.html',
        ),
        name='email_verified'
    ),
    path('password_set_message',
        TemplateView.as_view(
            template_name='accounts/password_set_message.html'
        ),
        name='password_set_message',
    ),
    path('company/<int:pk>/settings/',
        views.UpdateCompany.as_view(),
        name='company_settings',
    )
]

eventage/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static


from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path(
        '',
        views.HomeView.as_view(),
        name='home'
    ),
    path(
        'accounts/',
        include(
            'accounts.urls',
            namespace='accounts'
        )
    ),
    path(
        'accounts/',
        include(
            'django.contrib.auth.urls'
        )
    ),
    path(
        'events/',
        include(
            'pageGenerator.urls',
            namespace='pageGenerator'
        )
    ),
    path('error-404/',
        TemplateView.as_view(template_name='error_404.html'),
        name='error_404',
    ),
    path('error-403/',
        TemplateView.as_view(template_name='error_403.html'),
        name='error_403',
    ),
    path('thankyou/',
        TemplateView.as_view(template_name='thankyou.html'),
        name='thankyou',
    ),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pageGenerator/urls.py
from django.urls import path

from . import views

app_name = 'pageGenerator'

urlpatterns = [
    path(
        'new/',
        views.EventCreateView.as_view(),
        name='new-event'
    ),
    path(
        '<int:pk>/update/',
        views.EventUpdateView.as_view(),
        name='event-update'
    ),
    path(
        'list/',
        views.EventListView.as_view(),
        name='event-list'
    ),
    path(
        '<int:pk>/detail/',
        views.EventDetailView.as_view(),
        name='event-detail'
    ),
    path(
        'event/<str:token>/speaker-form/',
        views.SpeakerCreateView.as_view(),
        name='speaker-form'
    ),
    path(
        'speaker/<int:pk>/update/',
        views.SpeakerUpdateView.as_view(),
        name='speaker-update'
    ),
    path(
        '<int:pk>/<str:slug>/html/',
        views.HTMLPageView.as_view(),
        name='html-page'
    ),
    path(
        'fetch_image/<int:pk>/<int:img>/',
        views.fetch_image
    ),
]

pageGenerator/models.py
from django.db import models
from django.shortcuts import reverse
from django.db.models.signals import post_save
from django.dispatch import receiver

from datetime import datetime

from accounts import models as _models
# Create your models here.

class Event(models.Model):
    event_name = models.CharField(max_length=100, blank=False)
    venue = models.TextField(blank=True)
    start_date = models.DateField(blank=True, null=True)
    end_date = models.DateField(blank=True, null=True)
    company = models.ForeignKey(
        _models.Company,
        related_name='events',
        on_delete=models.CASCADE,
        blank=True,
        null=True
    )
    is_active = models.BooleanField(default=True)
    token = models.CharField(
        max_length=100,
        unique=True,
        null=True
    )
    images_per_row = models.PositiveIntegerField(
        default=5,
        blank=False,
        verbose_name='Images Per Row In Tile'
    )
    # html specific fields
    main_title = models.CharField(
        max_length=100,
        default='Thank You for Sharing Your Experience'
    )
    tickets_available = models.CharField(
        max_length=100,
        default='January 1'
    )
    promotion_period = models.CharField(
        max_length=200,
        default='January 1 - January 10'
    )
    promotional_text = models.TextField(
        default='<p>That means when your community members purchase the upgrade package at <strong>$XXX</strong> during the Default Pass purchasing period, you will receive $XXX for each course sold. </p> When members of your community purchases the upgrade package priced at $XXX during the Last Chance purchasing period, you will receive $XXX for each course sold. You can use the copy, images and Social Media posts below without using an Affiliate link of any kind.'
    )
    email_copy = models.TextField(
        default='If you are an Affiliate, you must insert your unique tracking link into the text where it says [ INSERT AFFILIATE LINK...]. If you don’t include your link, we will not be able to track clicks or pay commissions. If you are not an Affiliate, please feel free to delete all of the references to the links.'
    )
    event_slogan_poster = models.ImageField(
        upload_to='pageGenerator/event_slogan_poster/',
        default='pageGenerator/event_slogan_poster/default.jpg'
    )
    event_logo = models.ImageField(
        upload_to='pageGenerator/event_logo/',
        default='pageGenerator/event_logo/event.png',
    )
    event_poster_image = models.ImageField(
        upload_to='pageGenerator/event_poster_image/',
        default='pageGenerator/event_poster_image/default.jpeg'
    )
    host_title = models.CharField(
        max_length=100,
        default='Event Host'
    )
    poster_title = models.CharField(
        max_length=100,
        default='Jan 12-14: Wisdom in times such as these'
    )
    speaker_tile = models.ImageField(
        upload_to='pageGenerator/tile/',
        default='pageGenerator/tile/default.jpeg'
    )
    poster_image_background = models.ImageField(
        upload_to='pageGenerator/logo_background/',
        default='pageGenerator/logo_background/default.jpg'
    )
    footer_background = models.ImageField(
        upload_to='pageGenerator/footer_image/',
        default='pageGenerator/footer_image/default.jpeg'
    )

    def __str__(self):
        return self.event_name

    def get_absolute_url(self):
        return reverse(
            'pageGenerator:event-detail',
            kwargs={'pk': self.pk}
        )

class EventPass(models.Model):
    event = models.ForeignKey(
        Event,
        related_name='passes',
        on_delete=models.CASCADE
    )
    name = models.CharField(
        max_length=100,
        blank=False,
        verbose_name='Pass Name'
    )
    price = models.PositiveIntegerField(
        blank=False
    )
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.name

class EventSession(models.Model):
    event = models.ForeignKey(
        Event,
        related_name='sessions',
        on_delete=models.CASCADE
    )
    day_or_session = models.CharField(
        max_length=100,
        blank=False
    )
    title = models.CharField(
        max_length=100,
        blank=False
    )
    subtitle = models.CharField(
        max_length=100,
        blank=False
    )
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.day_or_session

class EventExtraFieldResponse(models.Model):
    event = models.ForeignKey(
        Event,
        related_name='extra_fields',
        on_delete=models.CASCADE
    )
    question = models.ForeignKey(
        _models.EventExtraField,
        related_name='responses',
        on_delete=models.CASCADE
    )
    response = models.CharField(
        max_length=200,
        blank=True
    )

    def __str__(self):
        if self.question.type == '2':
            return datetime.strftime(datetime.strptime(
                self.response, '%Y-%m-%d'
            ), '%b %d, %Y')
        return self.response

class Speaker(models.Model):
    name = models.CharField(
        max_length=100,
        blank=False
    )
    email = models.CharField(
        max_length=100,
        blank=True
    )
    contact = models.CharField(
        max_length=13,
        blank=True
    )
    profession = models.CharField(
        max_length=100,
        blank=True
    )
    organisation = models.CharField(
        max_length=100,
        blank=True
    )
    image = models.ImageField(
        verbose_name='Image for posters',
        upload_to='pageGenerator/speaker_image/',
        blank=False
    )

    def __str__(self):
        return self.name

class EventSpeaker(models.Model):
    event = models.ForeignKey(
        Event,
        related_name='speakers',
        on_delete=models.CASCADE,
    )
    session = models.ForeignKey(
        EventSession,
        related_name='speakers',
        on_delete=models.CASCADE,
        blank=True,
        null=True
    )
    name = models.CharField(
        max_length=100,
        blank=False
    )
    email = models.EmailField(
        max_length=100,
        blank=True
    )
    contact = models.CharField(
        max_length=13,
        blank=True
    )
    profession = models.CharField(
        max_length=100,
        blank=True
    )
    organisation = models.CharField(
        max_length=100,
        blank=True
    )
    image = models.ImageField(
        verbose_name='Image for posters',
        upload_to='pageGenerator/speaker_image/',
        default='pageGenerator/speaker_image/images.jpeg'
    )
    fb_image = models.ImageField(
        upload_to='pageGenerator/fb/',
        default='pageGenerator/fb/default.jpeg'
    )
    ig_image = models.ImageField(
        upload_to='pageGenerator/ig/',
        default='pageGenerator/ig/default.jpeg'
    )
    story_image = models.ImageField(
        upload_to='pageGenerator/story/',
        default='pageGenerator/story/default.jpeg'
    )
    chat_host = models.BooleanField(default=False)
    is_active = models.BooleanField(
        default=True,
        verbose_name='Status'
    )
    in_tile = models.BooleanField(
        default=True,
        verbose_name='In Speakers Tile?'
    )

    def __str__(self):
        return self.name

@receiver(post_save, sender=Event)
def create_defaults(sender, instance, created, **kwargs):
    if created:
        default_pass = EventPass.objects.create(
            event=instance,
            name='Default Pass',
            price=250
        )
        default_session = EventSession.objects.create(
            event=instance,
            day_or_session='Day 1',
            title='Introduction to Event: First Session',
            subtitle='First Session: January 12 starts at 12:00 EST'
        )
        default_speaker = EventSpeaker.objects.create(
            event=instance,
            session=default_session,
            name='Default User',
        )
        chat_host = EventSpeaker.objects.create(
            event=instance,
            session=default_session,
            name='Default User',
            chat_host=True
        )

class AdditionalSpeakerField(models.Model):
    event = models.ForeignKey(
        Event,
        related_name='additional_speaker_fields',
        on_delete=models.CASCADE
    )
    name = models.CharField(
        max_length=100,
        blank=False
    )
    type = models.CharField(
        max_length=100,
        choices=_models.FIELD_TYPE_CHOICES,
        default='1'
    )
    dropdown_choices = models.TextField(blank=True)

    def __Str__(self):
        return self.name

class AdditionalSpeakerFieldResponse(models.Model):
    field = models.ForeignKey(
        AdditionalSpeakerField,
        related_name='responses',
        on_delete=models.CASCADE
    )
    speaker = models.ForeignKey(
        EventSpeaker,
        related_name='additional_field_response',
        on_delete=models.CASCADE
    )
    response = models.CharField(
        max_length=100,
        blank=False
    )

pageGenerator/templates/pageGenerator/event_form.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
New Event
{% endblock %}

{% block css %}
  <link rel="stylesheet" type="text/css" href="{% static 'assets/libs/bootstrap-switch/dist/css/bootstrap3/bootstrap-switch.min.css' %}">
  <style media="screen">
    label{
      margin-bottom: -0.5rem;
    }

    .noresize{
      resize: none;
    }
  </style>
{% endblock %}

{% block breadcrumb %}
New Event Form
{% endblock %}

{% block content %}
  <div class="page-content container-fluid">
    <div class="row">
      <div class="col-lg-6 col-xlg-6 col-md-6 col-sm-12 col-xs-12 mx-auto">
          <div class="card">
            <h4 class="p-2 card-title bg-info text-white self-align-center">New Event Details</h4>
            <div class="card-body">
              <form method="post">
                {% csrf_token %}
                <table class="table table-borderless">
                  <tbody>
                    {% for field in form %}
                      <tr>
                        <th>{{field.label_tag}}</th>
                        <td>{{field}}</td>
                      </tr>
                    {% endfor %}
                  </tbody>
                </table>
                <input type="submit" class="btn btn-outline-success btn-sm btn-rounded float-right ml-2" name="submit_event" value="Create New Event">
                <a href="javascript:void(0)" class="btn btn-outline-info btn-sm btn-rounded float-right">Cancel</a>
              </form>
            </div>
          </div>
      </div>
    </div>
  </div>
{% endblock %}

pageGenerator/templates/pageGenerator/event_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Events
{% endblock %}

{% block css %}
  <link rel="stylesheet" type="text/css" href="{% static 'assets/libs/bootstrap-switch/dist/css/bootstrap3/bootstrap-switch.min.css' %}">
  <style media="screen">
    label{
      margin-bottom: -0.5rem;
    }

    .noresize{
      resize: none;
    }
  </style>
{% endblock %}

{% block breadcrumb %}
  Events
{% endblock %}

{% block buttons %}
  <li class="breadcrumb-item">
    <a class="float-right breadcrumb-link" href="{% url 'pageGenerator:new-event' %}">
      <button type="button" class="btn btn-outline-success btn-sm btn-rounded" name="button"><i class="fa fa-plus"></i> New Event</button>
    </a>
  </li>
{% endblock %}

{% block content %}
  <div class="page-content container-fluid">
    <div class="row">
      {% for event in events %}
      <div class="col-lg-3 col-xlg-3 col-md-3 col-sm-6 col-xs-12">
          <a href="{% url 'pageGenerator:event-detail' pk=event.pk %}">
            <div class="card">
                <div class="card-body">
                    <center> <img src="{% if event.event_logo %}{{event.event_logo.url}}{% else %}{% endif %}" class="rounded-circle" width="150" height="150" style="object-fit:cover;" />
                        <h4 class="card-title mt-2">{{event}}</h4>
                    </center>
                    {% if user.is_superuser or user.type == '1' %}
                        <a href="javascript:void(0)" class="float-right"><i class="mdi mdi-pencil " style="font-size:1.2em;"></i></a>
                    {% endif %}
                </div>
            </div>
          </a>
      </div>
      {% endfor %}
    </div>

    {% comment %}
    {% if inactive_users|length != 0 %}
      <div class="row mx-auto">
        <div class="card">
          <div class="card-body">
            <h4 class="card-title">Inactive Users List</h4>
          </div>
          <div class="card-body border-top">
            <div class="row pt-3">
              <div class="col-md-12 col-lg-12 col-sm-12">
                <div class="list-group">
                  {% for item in inactive_users %}
                    <li class="list-group-item"><a href="javascript:void(0)" data-toggle="modal" data-target="#userUpdateModal" onclick="populateUpdateForm({{item.pk}})">{{item.name}}</a></li>
                  {% endfor %}
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    {% endif %}
    {% endcomment %}

  </div>
{% endblock %}

{% block js %}
  <script src="{% static 'assets/libs/bootstrap-switch/dist/js/bootstrap-switch.min.js' %}"></script>
  <script>
    $(".bt-switch input[type='checkbox']").bootstrapSwitch();
    var radioswitch = function() {
        var bt = function() {
            $(".radio-switch").on("switch-change", function() {
                $(".radio-switch").bootstrapSwitch("toggleRadioState")
            }), $(".radio-switch").on("switch-change", function() {
                $(".radio-switch").bootstrapSwitch("toggleRadioStateAllowUncheck")
            }), $(".radio-switch").on("switch-change", function() {
                $(".radio-switch").bootstrapSwitch("toggleRadioStateAllowUncheck", !1)
            })
        };
        return {
            init: function() {
                bt()
            }
        }
    }();
    $(document).ready(function() {
        radioswitch.init()
    });
    </script>
{% endblock %}

pageGenerator/templates/pageGenerator/speaker-form.html
<!DOCTYPE html>
{% load static %}
{% load filters %}
{% load widget_tweaks %}
<html dir="ltr">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- Favicon icon -->
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'assets/images/logos/logo.png' %}">
    <title>Speaker Form</title>
	<link rel="canonical" href="https://www.wrappixel.com/templates/ampleadmin/" />

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.3.0/css/datepicker.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/cropperjs/1.5.7/cropper.min.css">

    <!-- Custom CSS -->
    <link href="{% static 'dist/css/style.min.css' %}" rel="stylesheet">

    <style media="screen">
    .modal-dialog{
        position: relative;
        display: table; /* This is important */
        overflow-y: auto;
        overflow-x: auto;
        width: auto;
        min-width: 300px;
    }

    /* .modal-dialog {
        max-width: 100%;
        width: auto !important;
        display: inline-block;
        overflow-y: auto;
    } */

    /* @media (min-width: 576px)
    {
      .modal-dialog {
          max-width: 100%;
          width: auto !important;
          margin: 1.75rem auto;
      }
    } */

    /* .modal {
      z-index: -1;
      display: flex !important;
      justify-content: center;
      align-items: center;
    }

    .modal-open .modal {
       z-index: 1050;
    } */

    /* .modal {
        min-width: auto;
        max-width: fit-content;
    } */

    label {
      margin-bottom: -0.5rem!important;
    }
    </style>
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
<![endif]-->
</head>

<body>
    <div class="main-wrapper">
        <!-- ============================================================== -->
        <!-- Preloader - style you can find in spinners.css -->
        <!-- ============================================================== -->
        <div class="preloader">
            <div class="lds-ripple">
                <div class="lds-pos"></div>
                <div class="lds-pos"></div>
            </div>
        </div>
        <!-- ============================================================== -->
        <!-- Preloader - style you can find in spinners.css -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Login box.scss -->
        <!-- ============================================================== -->
        <div class="auth-wrapper d-flex no-block justify-content-center align-items-center" style="background:#f6f6f6;">
            <div class="auth-box" style="margin-top:3%!important;margin-bottom:3%!important;">
                <div id="loginform">
                    <div class="logo">
                        <span class="db"><img src="{{event.event_logo.url}}" alt="homepage" class="light-logo" height="100" width="100" /></span>
                        <h4 class="font-medium mt-3">{{event.event_name}}</h4>
                        <h5 class="font-medium mb-3 mt-3">REGISTRATION FORM</h5>
                    </div>
                    <!-- Form -->
                    <div class="row">
                        <div class="col-12">
                            <form class="form-horizontal mt-3" method="post" enctype="multipart/form-data" id="formUpload">
                                {% csrf_token %}
                                <small style="color:red;">{{form.non_field_errors | striptags}}</small>
                                {% for field in form %}
                                  {% if field.field.widget.input_type != 'hidden' %}
                                    <small><label>{{field.label_tag}}</label></small>
                                    <small style="color:red;">{{field.errors | striptags}}</small>
                                    <div class="input-group mb-3">
                                        {{field}}
                                    </div>
                                  {% else %}
                                    {{field}}
                                  {% endif %}
                                {% endfor %}
                                <div class="form-group text-center">
                                    <div class="col-xs-12 pb-3">
                                        <input class="btn btn-block btn-info" type="submit" value="REGISTER">
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div id="modalCrop" class="modal" tabindex="-1" data-keyboard="false" data-backdrop="static" role="dialog" aria-labelledby="myModalLabel" aria-modal="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title" id="myModalLabel">Crop Image</h4>
                    {% comment %}
                      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                    {% endcomment %}
                </div>
                <div class="modal-body">
                    <img src="" id="image" style="max-width: 100%;">
                </div>
                <div class="modal-footer">
                  <div class="btn-group float-left" role="group">
                    <button type="button" class="btn btn-secondary js-zoom-in">
                      <span class="fa fa-search-plus"></span>
                    </button>
                    <button type="button" class="btn btn-secondary js-zoom-out">
                      <span class="fa fa-search-minus"></span>
                    </button>
                  </div>
                  {% comment %}
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                  {% endcomment %}
                  <button type="button" class="btn btn-primary js-crop-and-upload">Crop and Save</button>
                </div>
            </div>
        </div>
    </div>

    {# <!-- MODAL TO CROP THE IMAGE -->
    <div class="modal fade" id="modalCrop">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h4 class="modal-title">Crop the photo</h4>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <img src="" id="image" style="max-width: 100%;">
          </div>
          <div class="modal-footer">
            <div class="btn-group float-left" role="group">
              <button type="button" class="btn btn-default js-zoom-in">
                <span class="fa fa-search-plus"></span>
              </button>
              <button type="button" class="btn btn-default js-zoom-out">
                <span class="fa fa-search-minus"></span>
              </button>
            </div>
            <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
            <button type="button" class="btn btn-primary js-crop-and-upload">Crop and Save</button>
          </div>
        </div>
      </div>
    </div> #}
    <!-- ============================================================== -->
    <!-- All Required js -->
    <!-- ============================================================== -->
    <script src="{% static 'assets/libs/jquery/dist/jquery.min.js' %}"></script>
    <!-- Bootstrap tether Core JavaScript -->
    <script src="{% static 'assets/libs/popper.js/dist/umd/popper.min.js' %}"></script>
    <script src="{% static 'assets/libs/bootstrap/dist/js/bootstrap.min.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.3.0/js/bootstrap-datepicker.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/cropperjs/1.5.7/cropper.min.js"></script>
    <script src="{% static 'dist/js/jquery-cropper.min.js' %}"></script>
    <!-- ============================================================== -->
    <!-- This page plugin js -->
    <!-- ============================================================== -->
    <script>
    $('[data-toggle="tooltip"]').tooltip();
    $(".preloader").fadeOut();
    // ==============================================================
    // Login and Recover Password
    // ==============================================================
    $('#to-recover').on("click", function() {
        $("#loginform").slideUp();
        $("#recoverform").fadeIn();
    });

    $(function () {

      /* SCRIPT TO OPEN THE MODAL WITH THE PREVIEW */
      $("#id_image").change(function () {
        // ...
        if (this.files && this.files[0]) {
          var reader = new FileReader();
          reader.onload = function (e) {
            $("#image").attr("src", e.target.result);
            $("#modalCrop").modal("show");
          }
          reader.readAsDataURL(this.files[0]);
        }
      });

      /* SCRIPTS TO HANDLE THE CROPPER BOX */
      var $image = $("#image");
      // ...
      var cropBoxData;
      var canvasData;
      $("#modalCrop").on("shown.bs.modal", function () {
        $image.cropper({
          viewMode: 1,
          aspectRatio: 1/1,
          minCropBoxWidth: 200,
          minCropBoxHeight: 200,
          ready: function () {
            $image.cropper("setCanvasData", canvasData);
            $image.cropper("setCropBoxData", cropBoxData);
          }
        });
      }).on("hidden.bs.modal", function () {
        cropBoxData = $image.cropper("getCropBoxData");
        canvasData = $image.cropper("getCanvasData");
        $image.cropper("destroy");
      });

      // Enable zoom in button
      $(".js-zoom-in").click(function () {
        $image.cropper("zoom", 0.1);
      });

      // Enable zoom out button
      $(".js-zoom-out").click(function () {
        $image.cropper("zoom", -0.1);
      });

      /* SCRIPT TO COLLECT THE DATA AND POST TO THE SERVER */
      $(".js-crop-and-upload").click(function () {
        // ...
        var cropData = $image.cropper("getData");
        $("#id_x").val(cropData["x"]);
        $("#id_y").val(cropData["y"]);
        $("#id_height").val(cropData["height"]);
        $("#id_width").val(cropData["width"]);
        $('#modalCrop').modal('hide');
      });

    });

    // $('#modalCrop').on('show.bs.modal', function () {
    //    $(this).find('.modal-body').css({
    //           width:'auto',
    //           height:'auto',
    //           'max-height':'100%'
    //    });
    // });

    $(document).ready(() => {
      $('.mydatepicker').datepicker({
          format: 'dd/mm/yyyy',
          todayHighlight: true,
          autoclose:true
      });
    })
    </script>
</body>

</html>